CREATE TABLE IF NOT EXISTS tb_schedule (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  description TEXT,
  creator_id INTEGER NOT NULL,
  created_by varchar(50) NOT NULL,
  created_date TIMESTAMP NOT NULL,

  primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_session (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  active boolean,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  schedule_id INTEGER,

  foreign key (schedule_id) references tb_schedule(id),

  primary key (id)
);